/*
 Navicat Premium Data Transfer

 Source Server         : LocalHost
 Source Server Type    : MariaDB
 Source Server Version : 100523
 Source Host           : localhost:3366
 Source Schema         : db_ecommerce

 Target Server Type    : MariaDB
 Target Server Version : 100523
 File Encoding         : 65001

 Date: 01/04/2024 13:56:36
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `sku` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `unit_price` decimal(13,2) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `active` bit(1) DEFAULT b'1',
  `units_in_stock` int(11) DEFAULT NULL,
  `date_created` datetime(6) DEFAULT NULL,
  `last_updated` datetime(6) DEFAULT NULL,
  `category_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- ----------------------------
-- Records of product
-- ----------------------------
BEGIN;
INSERT INTO `product` VALUES (1, 'BOOK-TECH-1000', 'Crash Course in Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 14.99, 'assets/img/products/books/book-luv2code-1000.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (2, 'BOOK-TECH-1001', 'Become a Guru in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 20.99, 'assets/img/products/books/book-luv2code-1001.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (3, 'BOOK-TECH-1002', 'Exploring Vue.js', 'Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 14.99, 'assets/img/products/books/book-luv2code-1002.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (4, 'BOOK-TECH-1003', 'Advanced Techniques in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 13.99, 'assets/img/products/books/book-luv2code-1003.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (5, 'BOOK-TECH-1004', 'Crash Course in Big Data', 'Learn Big Data at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 18.99, 'assets/img/products/books/book-luv2code-1004.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (6, 'BOOK-TECH-1005', 'JavaScript Cookbook', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 23.99, 'assets/img/products/books/book-luv2code-1005.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (7, 'BOOK-TECH-1006', 'Beginners Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 14.99, 'assets/img/products/books/book-luv2code-1006.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (8, 'BOOK-TECH-1007', 'Advanced Techniques in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 16.99, 'assets/img/products/books/book-luv2code-1007.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (9, 'BOOK-TECH-1008', 'Introduction to Spring Boot', 'Learn Spring Boot at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 25.99, 'assets/img/products/books/book-luv2code-1008.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (10, 'BOOK-TECH-1009', 'Become a Guru in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 23.99, 'assets/img/products/books/book-luv2code-1009.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (11, 'BOOK-TECH-1010', 'Beginners Guide to Data Science', 'Learn Data Science at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 24.99, 'assets/img/products/books/book-luv2code-1010.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (12, 'BOOK-TECH-1011', 'Advanced Techniques in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 19.99, 'assets/img/products/books/book-luv2code-1011.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (13, 'BOOK-TECH-1012', 'Exploring DevOps', 'Learn DevOps at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 24.99, 'assets/img/products/books/book-luv2code-1012.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (14, 'BOOK-TECH-1013', 'The Expert Guide to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 19.99, 'assets/img/products/books/book-luv2code-1013.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (15, 'BOOK-TECH-1014', 'Introduction to SQL', 'Learn SQL at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 22.99, 'assets/img/products/books/book-luv2code-1014.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (16, 'BOOK-TECH-1015', 'The Expert Guide to JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 22.99, 'assets/img/products/books/book-luv2code-1015.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (17, 'BOOK-TECH-1016', 'Exploring React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 27.99, 'assets/img/products/books/book-luv2code-1016.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (18, 'BOOK-TECH-1017', 'Advanced Techniques in React.js', 'Learn React.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 13.99, 'assets/img/products/books/book-luv2code-1017.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (19, 'BOOK-TECH-1018', 'Introduction to C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 26.99, 'assets/img/products/books/book-luv2code-1018.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (20, 'BOOK-TECH-1019', 'Crash Course in JavaScript', 'Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 13.99, 'assets/img/products/books/book-luv2code-1019.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (21, 'BOOK-TECH-1020', 'Introduction to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 19.99, 'assets/img/products/books/book-luv2code-1020.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (22, 'BOOK-TECH-1021', 'Become a Guru in Java', 'Learn Java at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 18.99, 'assets/img/products/books/book-luv2code-1021.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (23, 'BOOK-TECH-1022', 'Introduction to Python', 'Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 26.99, 'assets/img/products/books/book-luv2code-1022.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (24, 'BOOK-TECH-1023', 'Advanced Techniques in C#', 'Learn C# at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 22.99, 'assets/img/products/books/book-luv2code-1023.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (25, 'BOOK-TECH-1024', 'The Expert Guide to Machine Learning', 'Learn Machine Learning at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!', 16.99, 'assets/img/products/books/book-luv2code-1024.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 1);
INSERT INTO `product` VALUES (26, 'COFFEEMUG-1000', 'Coffee Mug - Express', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1000.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (27, 'COFFEEMUG-1001', 'Coffee Mug - Cherokee', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1001.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (28, 'COFFEEMUG-1002', 'Coffee Mug - Sweeper', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1002.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (29, 'COFFEEMUG-1003', 'Coffee Mug - Aspire', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1003.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (30, 'COFFEEMUG-1004', 'Coffee Mug - Dorian', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1004.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (31, 'COFFEEMUG-1005', 'Coffee Mug - Columbia', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1005.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (32, 'COFFEEMUG-1006', 'Coffee Mug - Worthing', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1006.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (33, 'COFFEEMUG-1007', 'Coffee Mug - Oak Cliff', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1007.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (34, 'COFFEEMUG-1008', 'Coffee Mug - Tachyon', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1008.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (35, 'COFFEEMUG-1009', 'Coffee Mug - Pan', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1009.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (36, 'COFFEEMUG-1010', 'Coffee Mug - Phase', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1010.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (37, 'COFFEEMUG-1011', 'Coffee Mug - Falling', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1011.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (38, 'COFFEEMUG-1012', 'Coffee Mug - Wispy', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1012.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (39, 'COFFEEMUG-1013', 'Coffee Mug - Arlington', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1013.png', b'1', 100, '2024-04-01 13:47:02.000000', NULL, 2);
INSERT INTO `product` VALUES (40, 'COFFEEMUG-1014', 'Coffee Mug - Gazing', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1014.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (41, 'COFFEEMUG-1015', 'Coffee Mug - Azura', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1015.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (42, 'COFFEEMUG-1016', 'Coffee Mug - Quantum Leap', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1016.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (43, 'COFFEEMUG-1017', 'Coffee Mug - Light Years', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1017.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (44, 'COFFEEMUG-1018', 'Coffee Mug - Taylor', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1018.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (45, 'COFFEEMUG-1019', 'Coffee Mug - Gracia', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1019.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (46, 'COFFEEMUG-1020', 'Coffee Mug - Relax', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1020.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (47, 'COFFEEMUG-1021', 'Coffee Mug - Windermere', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1021.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (48, 'COFFEEMUG-1022', 'Coffee Mug - Prancer', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1022.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (49, 'COFFEEMUG-1023', 'Coffee Mug - Recursion', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1023.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (50, 'COFFEEMUG-1024', 'Coffee Mug - Treasure', 'Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!', 18.99, 'assets/img/products/coffeemugs/coffeemug-luv2code-1024.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 2);
INSERT INTO `product` VALUES (51, 'MOUSEPAD-1000', 'Mouse Pad - Express', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1000.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (52, 'MOUSEPAD-1001', 'Mouse Pad - Cherokee', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1001.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (53, 'MOUSEPAD-1002', 'Mouse Pad - Sweeper', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1002.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (54, 'MOUSEPAD-1003', 'Mouse Pad - Aspire', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1003.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (55, 'MOUSEPAD-1004', 'Mouse Pad - Dorian', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1004.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (56, 'MOUSEPAD-1005', 'Mouse Pad - Columbia', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1005.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (57, 'MOUSEPAD-1006', 'Mouse Pad - Worthing', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1006.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (58, 'MOUSEPAD-1007', 'Mouse Pad - Oak Cliff', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1007.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (59, 'MOUSEPAD-1008', 'Mouse Pad - Tachyon', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1008.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (60, 'MOUSEPAD-1009', 'Mouse Pad - Pan', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1009.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (61, 'MOUSEPAD-1010', 'Mouse Pad - Phase', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1010.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (62, 'MOUSEPAD-1011', 'Mouse Pad - Falling', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1011.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (63, 'MOUSEPAD-1012', 'Mouse Pad - Wispy', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1012.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (64, 'MOUSEPAD-1013', 'Mouse Pad - Arlington', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1013.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (65, 'MOUSEPAD-1014', 'Mouse Pad - Gazing', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1014.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (66, 'MOUSEPAD-1015', 'Mouse Pad - Azura', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1015.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (67, 'MOUSEPAD-1016', 'Mouse Pad - Quantum Leap', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1016.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (68, 'MOUSEPAD-1017', 'Mouse Pad - Light Years', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1017.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (69, 'MOUSEPAD-1018', 'Mouse Pad - Taylor', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1018.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (70, 'MOUSEPAD-1019', 'Mouse Pad - Gracia', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1019.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (71, 'MOUSEPAD-1020', 'Mouse Pad - Relax', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1020.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (72, 'MOUSEPAD-1021', 'Mouse Pad - Windermere', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1021.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (73, 'MOUSEPAD-1022', 'Mouse Pad - Prancer', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1022.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (74, 'MOUSEPAD-1023', 'Mouse Pad - Recursion', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1023.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (75, 'MOUSEPAD-1024', 'Mouse Pad - Treasure', 'Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!', 17.99, 'assets/img/products/mousepads/mousepad-luv2code-1024.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 3);
INSERT INTO `product` VALUES (76, 'LUGGAGETAG-1000', 'Luggage Tag - Cherish', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1000.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (77, 'LUGGAGETAG-1001', 'Luggage Tag - Adventure', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1001.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (78, 'LUGGAGETAG-1002', 'Luggage Tag - Skyline', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1002.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (79, 'LUGGAGETAG-1003', 'Luggage Tag - River', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1003.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (80, 'LUGGAGETAG-1004', 'Luggage Tag - Trail Steps', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1004.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (81, 'LUGGAGETAG-1005', 'Luggage Tag - Blooming', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1005.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (82, 'LUGGAGETAG-1006', 'Luggage Tag - Park', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1006.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (83, 'LUGGAGETAG-1007', 'Luggage Tag - Beauty', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1007.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (84, 'LUGGAGETAG-1008', 'Luggage Tag - Water Fall', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1008.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (85, 'LUGGAGETAG-1009', 'Luggage Tag - Trail', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1009.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (86, 'LUGGAGETAG-1010', 'Luggage Tag - Skyscraper', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1010.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (87, 'LUGGAGETAG-1011', 'Luggage Tag - Leaf', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1011.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (88, 'LUGGAGETAG-1012', 'Luggage Tag - Jungle', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1012.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (89, 'LUGGAGETAG-1013', 'Luggage Tag - Shoreline', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1013.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (90, 'LUGGAGETAG-1014', 'Luggage Tag - Blossom', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1014.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (91, 'LUGGAGETAG-1015', 'Luggage Tag - Lock', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1015.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (92, 'LUGGAGETAG-1016', 'Luggage Tag - Cafe', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1016.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (93, 'LUGGAGETAG-1017', 'Luggage Tag - Darling', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1017.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (94, 'LUGGAGETAG-1018', 'Luggage Tag - Full Stack', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1018.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (95, 'LUGGAGETAG-1019', 'Luggage Tag - Courtyard', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1019.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (96, 'LUGGAGETAG-1020', 'Luggage Tag - Coaster', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1020.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (97, 'LUGGAGETAG-1021', 'Luggage Tag - Bridge', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1021.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (98, 'LUGGAGETAG-1022', 'Luggage Tag - Sunset', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1022.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (99, 'LUGGAGETAG-1023', 'Luggage Tag - Flames', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1023.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
INSERT INTO `product` VALUES (100, 'LUGGAGETAG-1024', 'Luggage Tag - Countryside', 'This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!', 16.99, 'assets/img/products/luggagetags/luggagetag-luv2code-1024.png', b'1', 100, '2024-04-01 13:47:03.000000', NULL, 4);
COMMIT;

-- ----------------------------
-- Table structure for product_category
-- ----------------------------
DROP TABLE IF EXISTS `product_category`;
CREATE TABLE `product_category` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `category_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

-- ----------------------------
-- Records of product_category
-- ----------------------------
BEGIN;
INSERT INTO `product_category` VALUES (1, 'Books');
INSERT INTO `product_category` VALUES (2, 'Coffee Mugs');
INSERT INTO `product_category` VALUES (3, 'Mouse Pads');
INSERT INTO `product_category` VALUES (4, 'Luggage Tags');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
